pipeline {
    agent none

    stages {

        stage('Node.js') {
            agent {
                docker {
                    image 'node:20'
                }
            }

            steps {
                sh 'echo "Node.js version:"'
                sh 'node --version'
                sh 'echo "Name: Shahzaib"'
            }
        }

        stage('Maven') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-17'
                }
            }

            steps {
                sh 'echo "Maven version:"'
                sh 'mvn --version'
                sh 'echo "Name: Shahzaib"'
            }
        }
    }
}