#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker_compose
- name: Install Docker Compose
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
    update_cache: true
